"""Generate the strata-tiny.zarr fixture for zarr-access tests.

Run when the fixture schema needs to change:
    cd packages/zarr-access/tests
    uv run python generate_strata_fixture.py

The generated bytes are committed to git. The frontend's
strata-tiny.zarr fixture in the cbioportal-cell-explorer repo uses the
SAME data shape — keep them in sync if you regenerate.
"""

from pathlib import Path
import shutil

import anndata as ad
import numpy as np
import pandas as pd

import cell2zarr.strata
from cell2zarr.strata import StrataConfig


FIXTURE_PATH = Path(__file__).parent / "fixtures" / "strata-tiny.zarr"


def build_synthetic_anndata() -> ad.AnnData:
    """50 cells × 10 genes, deterministic X, two categorical obs columns.

    X[i, j] = ((i + 1) * (j + 1)) % 5   -> integer values 0..4
    cell_type = 20 'A' + 20 'B' + 10 'C'
    donor = alternating 'd1'/'d2'

    Atomic axes (cell_type, donor) -> 6 strata.
    Coarse axes (cell_type)        -> 3 strata.
    """
    X = np.fromfunction(
        lambda i, j: ((i + 1) * (j + 1)) % 5,
        shape=(50, 10),
    ).astype(np.float16)
    cell_types = ["A"] * 20 + ["B"] * 20 + ["C"] * 10
    donors = ["d1" if (i % 2) == 0 else "d2" for i in range(50)]
    obs = pd.DataFrame({
        "cell_type": pd.Categorical(cell_types),
        "donor": pd.Categorical(donors),
    })
    var = pd.DataFrame(index=[f"gene{i+1}" for i in range(10)])
    return ad.AnnData(X=X, obs=obs, var=var)


def main() -> None:
    if FIXTURE_PATH.exists():
        shutil.rmtree(FIXTURE_PATH)
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)

    adata = build_synthetic_anndata()
    # Match cell-explorer production format: zarr v3.
    ad.settings.zarr_write_format = 3
    adata.write_zarr(FIXTURE_PATH)
    print(f"wrote {FIXTURE_PATH}")

    config = StrataConfig(
        atomic_axes=["cell_type", "donor"],
        coarse=[["cell_type"]],
        force=True,
    )
    cell2zarr.strata.build_strata(FIXTURE_PATH, config)
    print(f"strata built on {FIXTURE_PATH}")


if __name__ == "__main__":
    main()
