# generated by datamodel-codegen:
#   filename:  app_config.schema.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, PositiveFloat, confloat


class Filter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ids: list[str]
    obsColumn: str


class FilterByExpression(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    gene: str
    min: float | None = None
    max: float | None = None


class Viewport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    target: list[Any]
    zoom: float


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: str | None = None
    dataset: str | None = None
    embedding: str | None = None
    colorBy: Literal['gene', 'category'] | None = None
    gene: str | None = None
    category: str | None = None
    colorScaleName: Literal['viridis', 'magma', 'plasma', 'inferno'] | None = None
    highlightedCategories: list[str] | None = None
    geneLabelColumn: str | None = None
    filter: Filter | None = None
    filterByExpression: FilterByExpression | None = None
    viewport: Viewport | None = None
    fitViewportToSelection: bool | None = None
    pointSize: PositiveFloat | None = None
    opacity: confloat(ge=0.0, le=1.0) | None = None
    summaryObsColumns: list[str] | None = None
    summaryGenes: list[str] | None = None
    removeSummaryObsColumns: list[str] | None = None
    removeSummaryGenes: list[str] | None = None
    summaryContext: Literal['overall', 'selections'] | None = None
    selectionDisplayMode: Literal['dim', 'hide'] | None = None
    showCategoryLabels: bool | None = None
    showHeader: bool | None = None
    showLeftSidebar: bool | None = None
    showRightSidebar: bool | None = None
    showDatasetDropdown: bool | None = None
