"""add datasource internal_base_url

Revision ID: 8b08cae0722d
Revises: da664672edd0
Create Date: 2026-05-12 12:30:19.511144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b08cae0722d'
down_revision: Union[str, Sequence[str], None] = 'da664672edd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasources', sa.Column('internal_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasources', 'internal_base_url')
    # ### end Alembic commands ###
