"""add collections

Revision ID: aae63119b18e
Revises: 3c0b287b2d76
Create Date: 2026-08-13 06:50:06.736125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aae63119b18e'
down_revision: Union[str, Sequence[str], None] = '3c0b287b2d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publication_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publication_citation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_slug'), 'collections', ['slug'], unique=True)
    # SQLite can't ALTER TABLE to add a constraint directly — batch mode
    # rebuilds the table via copy-and-move to add the FK with ondelete.
    with op.batch_alter_table('datasets') as batch_op:
        batch_op.add_column(sa.Column('collection_id', sa.Uuid(), nullable=True))
        batch_op.create_index(
            op.f('ix_datasets_collection_id'), ['collection_id'], unique=False
        )
        batch_op.create_foreign_key(
            'fk_datasets_collection_id',
            'collections', ['collection_id'], ['id'], ondelete='SET NULL',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets') as batch_op:
        batch_op.drop_constraint('fk_datasets_collection_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_datasets_collection_id'))
        batch_op.drop_column('collection_id')
    op.drop_index(op.f('ix_collections_slug'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
