"""add chat threads and messages

Revision ID: db60f1496e9a
Revises: e0e15767da8e
Create Date: 2026-05-12 17:03:34.932464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db60f1496e9a'
down_revision: Union[str, Sequence[str], None] = 'e0e15767da8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_dataset_id'), 'chat_threads', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_user_sub'), 'chat_threads', ['user_sub'], unique=False)
    op.create_index(
        'idx_chat_threads_user_dataset_updated',
        'chat_threads',
        ['user_sub', 'dataset_id', sa.text('updated_at DESC')],
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_index(
        'idx_chat_messages_thread_created',
        'chat_messages',
        ['thread_id', 'created_at'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_messages_thread_created', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_chat_threads_user_dataset_updated', table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_dataset_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_user_sub'), table_name='chat_threads')
    op.drop_table('chat_threads')
    # ### end Alembic commands ###
